version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - misspell
    - revive
    - gosec
  exclusions:
    paths:
      - dist

formatters:
  enable:
    - gofmt
    - goimports
